
services:
  headless:
    image: headless-app
    container_name: headless-app
    environment:
      - ZERODHA_SECRET=${ZERODHA_SECRET}
    ports:
      - "7878:7878"
  server:
    image: server-app
    container_name: server-app
    environment:
      - ZERODHA_USER=${ZERODHA_USER}
      - ZERODHA_PASS=${ZERODHA_PASS}
      - ZERODHA_SECRET=${ZERODHA_SECRET}
      - ZERODHA_API_KEY=${ZERODHA_API_KEY}
      - ZERODHA_API_SECRET=${ZERODHA_API_SECRET}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5859:5859"
    volumes:
      - fs-data:/data
      # - fs-server:/app:rw
  timescaledb:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    restart: always
    environment:
      - PGDATA=/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}","-d", "${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 10
      start_period: 30s
    ports:
      - "5432:5432"
    volumes:
      - fs-pgsql:/pgdata
  pgadmin:
    image: dpage/pgadmin4:snapshot
    container_name: pgadmin4
    restart: always
    depends_on:
      timescaledb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 10
      start_period: 30s
    ports:
      - "6464:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - fs-pgadmin:/var/lib/pgadmin

volumes:
  fs-pgsql:
    driver: local
    driver_opts:
      type: none
      device: ./data/pgsql
      o: bind
  fs-pgadmin:
    driver: local
    driver_opts:
      type: none
      device: ./data/pg-admin
      o: bind
  fs-server:
    driver: local
    driver_opts:
      type: none
      device: ./server
      o: bind