// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TblCache struct {
	Key     string
	Value   pgtype.Text
	Created pgtype.Timestamptz
}

type TblSevenFifty struct {
	ID       int16
	Symbol   string
	FullName pgtype.Text
}
