// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCache = `-- name: CreateCache :exec
INSERT INTO tbl_cache (key, value, created)
VALUES ($1, $2, $3)
`

type CreateCacheParams struct {
	Key     string
	Value   pgtype.Text
	Created pgtype.Timestamptz
}

func (q *Queries) CreateCache(ctx context.Context, arg CreateCacheParams) error {
	_, err := q.db.Exec(ctx, createCache, arg.Key, arg.Value, arg.Created)
	return err
}

const deleteCache = `-- name: DeleteCache :exec
DELETE FROM tbl_cache
WHERE key = $1
`

func (q *Queries) DeleteCache(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteCache, key)
	return err
}

const getCache = `-- name: GetCache :one
SELECT key, value, created
FROM tbl_cache
WHERE key = $1
LIMIT 1
`

func (q *Queries) GetCache(ctx context.Context, key string) (TblCache, error) {
	row := q.db.QueryRow(ctx, getCache, key)
	var i TblCache
	err := row.Scan(&i.Key, &i.Value, &i.Created)
	return i, err
}

const listSymbols = `-- name: ListSymbols :many
SELECT id, symbol, full_name, instrument_token, exchange_token
FROM tbl_seven_fifty
WHERE instrument_token IS NOT NULL
ORDER BY id ASC
`

func (q *Queries) ListSymbols(ctx context.Context) ([]TblSevenFifty, error) {
	rows, err := q.db.Query(ctx, listSymbols)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TblSevenFifty
	for rows.Next() {
		var i TblSevenFifty
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.FullName,
			&i.InstrumentToken,
			&i.ExchangeToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCache = `-- name: UpdateCache :exec
UPDATE tbl_cache
SET value = $2
WHERE key = $1
`

type UpdateCacheParams struct {
	Key   string
	Value pgtype.Text
}

func (q *Queries) UpdateCache(ctx context.Context, arg UpdateCacheParams) error {
	_, err := q.db.Exec(ctx, updateCache, arg.Key, arg.Value)
	return err
}

const updateSymbols = `-- name: UpdateSymbols :exec
UPDATE tbl_seven_fifty
SET full_name = $2,
  instrument_token = $3,
  exchange_token = $4
WHERE symbol = $1
`

type UpdateSymbolsParams struct {
	Symbol          string
	FullName        pgtype.Text
	InstrumentToken pgtype.Int4
	ExchangeToken   pgtype.Int4
}

func (q *Queries) UpdateSymbols(ctx context.Context, arg UpdateSymbolsParams) error {
	_, err := q.db.Exec(ctx, updateSymbols,
		arg.Symbol,
		arg.FullName,
		arg.InstrumentToken,
		arg.ExchangeToken,
	)
	return err
}

const upsertCache = `-- name: UpsertCache :exec
INSERT INTO tbl_cache (key, value, created)
VALUES ($1, $2, $3) ON CONFLICT (key) DO
UPDATE
SET value = EXCLUDED.value,
  created = EXCLUDED.created
`

type UpsertCacheParams struct {
	Key     string
	Value   pgtype.Text
	Created pgtype.Timestamptz
}

func (q *Queries) UpsertCache(ctx context.Context, arg UpsertCacheParams) error {
	_, err := q.db.Exec(ctx, upsertCache, arg.Key, arg.Value, arg.Created)
	return err
}
